-- Admin broadcast events for connected console instances.
-- Used for low-frequency UI commands such as prompting all admins to refresh.

CREATE TABLE IF NOT EXISTS public.admin_broadcasts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_admin_broadcasts_created_at
  ON public.admin_broadcasts (created_at DESC);

ALTER TABLE public.admin_broadcasts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read admin broadcasts"
  ON public.admin_broadcasts FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert admin broadcasts"
  ON public.admin_broadcasts FOR INSERT
  WITH CHECK (
    auth.role() = 'authenticated'
    AND (created_by IS NULL OR created_by = auth.uid())
  );

ALTER PUBLICATION supabase_realtime ADD TABLE public.admin_broadcasts;
